# Generated by Django 5.1.6 on 2025-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/html/'),
        ),
        migrations.AddField(
            model_name='project',
            name='markdown_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/markdown/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/pdf/'),
        ),
    ]
