# Generated by Django 5.1.6 on 2025-04-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_project_html_file_project_markdown_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('pdf', 'PDF')], max_length=10)),
                ('file', models.FileField(upload_to='generated_docs/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.project')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
