# Generated by Django 5.1.6 on 2025-04-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_generateddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='doc_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='html_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='markdown_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pdf_file',
        ),
    ]
